In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import ExtraTreesClassifier

In [3]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep]

In [4]:
train_data = pd.read_csv("10sec_smooth_cropped_288feat.csv",index_col = 0)
train_data = clean_dataset(train_data)
train_data_shuffled = train_data.iloc[np.random.permutation(len(train_data))]


In [7]:
train_features_s = train_data_shuffled.copy()
print(train_features_s.shape)
train_labels_s = train_features_s["label"]
train_features_s = train_features_s.drop(["label"], axis = 1)
print(train_features_s.shape)

fs = ExtraTreesClassifier(random_state = 0)
fs.fit(train_features_s,train_labels_s)

feat_imps = fs.feature_importances_
print(feat_imps[:5])
sorted_feat_imps = np.sort(feat_imps)
print(feat_imps[:5])
print(sorted_feat_imps[-5:])

col_indices = [i for i, j in enumerate(feat_imps) if j in sorted_feat_imps[-60:]]

print(col_indices[:5])

print(len(col_indices))

cols = train_features_s.columns
print(len(cols))
imp_cols = [col for i,col in enumerate(cols) if i in col_indices]

print(imp_cols)

(3934, 289)
(3934, 288)
[0.03654173 0.04618197 0.00688974 0.00104264 0.00033469]
[0.03654173 0.04618197 0.00688974 0.00104264 0.00033469]
[0.03654173 0.03763104 0.03789311 0.03863896 0.04618197]
[0, 1, 2, 5, 6]
60
288
['mean_acc_x', 'mean_acc_y', 'mean_acc_z', 'std_acc_z', 'mad_acc_x', 'min_acc_x', 'min_acc_y', 'max_acc_x', 'max_acc_y', 'max_acc_z', 'em_acc_x', 'em_acc_y', 'em_acc_z', 'sma_acc', 'mean_macc', 'std_macc', 'mad_macc', 'max_macc', 'em_macc', 'iqr_macc', 'sma_macc', 'std_accj_z', 'mad_accj_x', 'iqr_accj_y', 'mean_macc_jerk', 'min_macc_jerk', 'iqr_macc_jerk', 'sma_macc_jerk', 'skew_mfacc', 'mean_faccj_y', 'mad_faccj_y', 'min_faccj_y', 'max_faccj_y', 'max_faccj_z', 'em_faccj_y', 'iqr_faccj_y', 'mean_mfacc_jerk', 'mad_mfacc_jerk', 'max_mfacc_jerk', 'mad_gy_x', 'mad_gy_y', 'mad_gy_z', 'min_gy_x', 'min_gy_z', 'em_gy_z', 'iqr_gy_x', 'iqr_gy_y', 'iqr_gy_z', 'sma_gy', 'mean_mgy', 'mad_mgy', 'mad_gyj_y', 'mad_gyj_z', 'iqr_gyj_y', 'sma_gyj', 'mad_mgy_jerk', 'min_mgy_jerk', 'skew_fgy_